from neat_cars.radars_car.fitness import *

VERBOSE = True
STDOUT_VERBOSE = True
SEED = 42

MAX_RADAR_DISTANCE = 100.0
TRAIN_RADARS_CAR = False
MODEL_DIR_RADARS_CAR = "out/radars_car"
N_GENERATIONS_RADARS_CAR = 2
TOTAL_STEPS_SIMULATION_RADARS_CAR = 200
NOISE_RADARS_CAR = 5
FITNESS_FUN_RADARS_CAR = tight_curves_fitness

